language: node_js
node_js:
- 8.10.0
cache:
  directories:
    - node_modules
before_install:
- ".travis/install.sh"
script:
- ".travis/build.sh"
- ".travis/test.sh"
after_success:
- ".travis/deploy.sh"
